services:
  web:
    container_name: ${DOCKER_CONTAINER_NAME_PREFIX}-web
    restart: always
    build: .
    env_file:
      - .env
    ports:
      - ${DJANGO_PORT}:8000
      # - static:/app/static
    volumes:
      - .:/app
    depends_on:
      - db

  db:
    container_name: ${DOCKER_CONTAINER_NAME_PREFIX}-db
    image: postgres:alpine
    shm_size: 128mb
    restart: always
    env_file:
      - .env
    environment:
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    ports:
      - ${POSTGRES_PORT}:5432
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
